import streamlit as st
from email import policy
from email.parser import BytesParser
import re
import ipaddress
from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet


# =========================================================
# PAGE CONFIGURATION
# =========================================================

st.set_page_config(
    page_title="Email Header Forensics",
    page_icon="🔎",
    layout="wide"
)


# =========================================================
# TITLE
# =========================================================

st.title("🔎 Email Header Forensics and Analysis Tool")

st.write(
    "A digital-forensics tool for analyzing raw email headers, "
    "routing information, IP addresses, authentication results, "
    "and potential forensic indicators."
)


# =========================================================
# INPUT
# =========================================================

st.subheader("📩 Email Header Input")

uploaded_file = st.file_uploader(
    "Upload a raw email/header file (.eml or .txt)",
    type=["eml", "txt"]
)

email_text = st.text_area(
    "Or paste the raw email header below:",
    height=280,
    placeholder="Paste raw email headers here..."
)


if uploaded_file is not None:
    try:
        email_text = uploaded_file.read().decode(
            "utf-8",
            errors="replace"
        )

        st.success(
            f"Loaded file: {uploaded_file.name}"
        )

    except Exception as e:
        st.error(
            f"Could not read the uploaded file: {e}"
        )


# =========================================================
# HELPER FUNCTIONS
# =========================================================

def extract_ips(text):
    """Extract valid IPv4 addresses."""
    
    pattern = r"\b(?:\d{1,3}\.){3}\d{1,3}\b"
    
    candidates = re.findall(
        pattern,
        text
    )

    valid_ips = []

    for ip in candidates:
        try:
            ipaddress.ip_address(ip)

            if ip not in valid_ips:
                valid_ips.append(ip)

        except ValueError:
            pass

    return valid_ips


def classify_ip(ip):
    """Classify IPv4 address for forensic display."""

    address = ipaddress.ip_address(ip)

    # Documentation/test ranges
    documentation_ranges = [
        ipaddress.ip_network("192.0.2.0/24"),
        ipaddress.ip_network("198.51.100.0/24"),
        ipaddress.ip_network("203.0.113.0/24")
    ]

    for network in documentation_ranges:
        if address in network:
            return "Documentation/Test"

    if address.is_loopback:
        return "Loopback"

    if address.is_link_local:
        return "Link-local"

    if address.is_private:
        return "Private"

    if address.is_reserved:
        return "Reserved"

    if address.is_global:
        return "Public/Global"

    return "Special-use"


def get_authentication_result(
    auth_header,
    method
):
    """Extract SPF, DKIM or DMARC result."""

    if not auth_header:
        return "Not found"

    pattern = rf"{method}\s*=\s*([a-zA-Z]+)"

    match = re.search(
        pattern,
        auth_header,
        re.IGNORECASE
    )

    if match:
        return match.group(1).lower()

    return "Not found"


def create_pdf_report(
    sender,
    recipient,
    subject,
    date_value,
    received_count,
    ips,
    servers,
    spf,
    dkim,
    dmarc,
    indicators
):
    """Create downloadable PDF forensic report."""

    buffer = BytesIO()

    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    heading_style = styles["Heading2"]
    body_style = styles["BodyText"]

    story = []

    story.append(
        Paragraph(
            "Email Header Forensics - Investigation Report",
            title_style
        )
    )

    story.append(
        Spacer(1, 15)
    )

    story.append(
        Paragraph(
            "Generated by Email Header Forensics and Analysis Tool",
            body_style
        )
    )

    story.append(
        Spacer(1, 20)
    )

    story.append(
        Paragraph(
            "1. Basic Information",
            heading_style
        )
    )

    basic_data = [
        ["Field", "Value"],
        ["From", sender],
        ["To", recipient],
        ["Subject", subject],
        ["Date", date_value],
        ["Received Hops", str(received_count)]
    ]

    basic_table = Table(
        basic_data,
        colWidths=[130, 350]
    )

    basic_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold")
        ])
    )

    story.append(basic_table)

    story.append(
        Spacer(1, 20)
    )

    story.append(
        Paragraph(
            "2. IP Address Analysis",
            heading_style
        )
    )

    if ips:

        ip_data = [
            ["IP Address", "Classification"]
        ]

        for ip in ips:
            ip_data.append([
                ip,
                classify_ip(ip)
            ])

        ip_table = Table(
            ip_data,
            colWidths=[180, 300]
        )

        ip_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold")
            ])
        )

        story.append(ip_table)

    else:

        story.append(
            Paragraph(
                "No IP addresses detected.",
                body_style
            )
        )

    story.append(
        Spacer(1, 20)
    )

    story.append(
        Paragraph(
            "3. Mail Server Information",
            heading_style
        )
    )

    if servers:

        for server in servers:

            story.append(
                Paragraph(
                    f"• {server}",
                    body_style
                )
            )

    else:

        story.append(
            Paragraph(
                "No mail servers extracted.",
                body_style
            )
        )

    story.append(
        Spacer(1, 20)
    )

    story.append(
        Paragraph(
            "4. Email Authentication",
            heading_style
        )
    )

    auth_data = [
        ["Authentication", "Result"],
        ["SPF", spf.upper()],
        ["DKIM", dkim.upper()],
        ["DMARC", dmarc.upper()]
    ]

    auth_table = Table(
        auth_data,
        colWidths=[180, 300]
    )

    auth_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold")
        ])
    )

    story.append(auth_table)

    story.append(
        Spacer(1, 20)
    )

    story.append(
        Paragraph(
            "5. Forensic Indicators",
            heading_style
        )
    )

    if indicators:

        for indicator in indicators:

            story.append(
                Paragraph(
                    f"• {indicator}",
                    body_style
                )
            )

    else:

        story.append(
            Paragraph(
                "No indicators were generated by the current rules.",
                body_style
            )
        )

    story.append(
        Spacer(1, 25)
    )

    story.append(
        Paragraph(
            "Important: These results are forensic indicators "
            "and should be correlated with additional evidence "
            "before drawing investigative conclusions.",
            body_style
        )
    )

    document.build(story)

    buffer.seek(0)

    return buffer


# =========================================================
# ANALYSIS
# =========================================================

if st.button("🔍 Analyze Email"):

    if not email_text.strip():

        st.warning(
            "Please paste an email header or upload an email file."
        )

    else:

        try:

            # -------------------------------------------------
            # PARSE EMAIL
            # -------------------------------------------------

            msg = BytesParser(
                policy=policy.default
            ).parsebytes(
                email_text.encode("utf-8")
            )

            st.success(
                "✅ Email header parsed successfully!"
            )


            # -------------------------------------------------
            # BASIC INFORMATION
            # -------------------------------------------------

            sender = msg.get(
                "From",
                "Not found"
            )

            recipient = msg.get(
                "To",
                "Not found"
            )

            subject = msg.get(
                "Subject",
                "Not found"
            )

            date_value = msg.get(
                "Date",
                "Not found"
            )

            message_id = msg.get(
                "Message-ID",
                "Not found"
            )

            reply_to = msg.get(
                "Reply-To",
                "Not found"
            )


            st.header("📋 Basic Information")

            col1, col2 = st.columns(2)

            with col1:

                st.write(
                    "**From:**",
                    sender
                )

                st.write(
                    "**To:**",
                    recipient
                )

                st.write(
                    "**Subject:**",
                    subject
                )

            with col2:

                st.write(
                    "**Date:**",
                    date_value
                )

                st.write(
                    "**Message-ID:**",
                    message_id
                )

                st.write(
                    "**Reply-To:**",
                    reply_to
                )


            # -------------------------------------------------
            # RECEIVED HEADERS
            # -------------------------------------------------

            st.header(
                "📬 Received Header Analysis"
            )

            received_headers = msg.get_all(
                "Received",
                []
            )

            if received_headers:

                st.write(
                    f"**Number of Received headers:** "
                    f"{len(received_headers)}"
                )

                for i, received in enumerate(
                    received_headers,
                    start=1
                ):

                    st.markdown(
                        f"### Hop {i}"
                    )

                    st.code(
                        received,
                        language="text"
                    )

            else:

                st.warning(
                    "No Received headers were found."
                )


            # -------------------------------------------------
            # IP ANALYSIS
            # -------------------------------------------------

            st.header(
                "🌐 IP Address Analysis"
            )

            all_ips = extract_ips(
                email_text
            )

            if all_ips:

                ip_data = []

                for ip in all_ips:

                    classification = classify_ip(
                        ip
                    )

                    ip_data.append([
                        ip,
                        classification
                    ])

                st.table(
                    {
                        "IP Address": [
                            row[0]
                            for row in ip_data
                        ],
                        "Classification": [
                            row[1]
                            for row in ip_data
                        ]
                    }
                )

            else:

                st.info(
                    "No valid IPv4 addresses were found."
                )


            # -------------------------------------------------
            # MAIL SERVERS
            # -------------------------------------------------

            st.header(
                "🖥️ Mail Server Information"
            )

            servers = []

            for received in received_headers:

                match = re.search(
                    r"from\s+([^\s(]+)",
                    received,
                    re.IGNORECASE
                )

                if match:

                    server = match.group(1)

                    if server not in servers:
                        servers.append(server)

            if servers:

                for server in servers:

                    st.write(
                        f"📨 **Mail Server:** {server}"
                    )

            else:

                st.info(
                    "No mail-server names could be extracted."
                )


            # -------------------------------------------------
            # AUTHENTICATION
            # -------------------------------------------------

            st.header(
                "🔐 Email Authentication Analysis"
            )

            auth_headers = msg.get_all(
                "Authentication-Results",
                []
            )

            auth_text = " ".join(
                auth_headers
            )

            spf_result = get_authentication_result(
                auth_text,
                "spf"
            )

            dkim_result = get_authentication_result(
                auth_text,
                "dkim"
            )

            dmarc_result = get_authentication_result(
                auth_text,
                "dmarc"
            )

            col1, col2, col3 = st.columns(3)

            with col1:

                st.metric(
                    "SPF",
                    spf_result.upper()
                )

            with col2:

                st.metric(
                    "DKIM",
                    dkim_result.upper()
                )

            with col3:

                st.metric(
                    "DMARC",
                    dmarc_result.upper()
                )


            # -------------------------------------------------
            # FORENSIC INDICATORS
            # -------------------------------------------------

            st.header(
                "⚠️ Forensic Indicators"
            )

            indicators = []


            if not received_headers:

                indicators.append(
                    "No Received headers were found."
                )


            if len(received_headers) > 5:

                indicators.append(
                    "A large number of Received headers "
                    "were detected. Review the routing chain carefully."
                )


            if spf_result == "fail":

                indicators.append(
                    "SPF authentication failed."
                )


            if dkim_result == "fail":

                indicators.append(
                    "DKIM authentication failed."
                )


            if dmarc_result == "fail":

                indicators.append(
                    "DMARC authentication failed."
                )


            if (
                spf_result == "Not found"
                and dkim_result == "Not found"
                and dmarc_result == "Not found"
            ):

                indicators.append(
                    "No SPF, DKIM, or DMARC result "
                    "was found in the supplied headers."
                )


            documentation_ips = []

            for ip in all_ips:

                if classify_ip(ip) == "Documentation/Test":

                    documentation_ips.append(ip)


            if documentation_ips:

                indicators.append(
                    "Documentation/test IP address(es) detected: "
                    + ", ".join(documentation_ips)
                    + ". These addresses are commonly used in examples and testing."
                )


            private_ips = []

            for ip in all_ips:

                if classify_ip(ip) == "Private":

                    private_ips.append(ip)


            if private_ips:

                indicators.append(
                    "Private IP address(es) detected: "
                    + ", ".join(private_ips)
                    + ". These may represent internal network infrastructure."
                )


            if indicators:

                for indicator in indicators:

                    st.warning(
                        "⚠️ " + indicator
                    )

            else:

                st.success(
                    "No immediate forensic indicators "
                    "were detected by the current rules."
                )


            # -------------------------------------------------
            # INVESTIGATION SUMMARY
            # -------------------------------------------------

            st.header(
                "📝 Investigation Summary"
            )

            st.write(
                f"""
**Email sender:** {sender}

**Recipient:** {recipient}

**Subject:** {subject}

**Received hops:** {len(received_headers)}

**IP addresses detected:** {len(all_ips)}

**SPF:** {spf_result.upper()}

**DKIM:** {dkim_result.upper()}

**DMARC:** {dmarc_result.upper()}
"""
            )


            # -------------------------------------------------
            # PDF REPORT
            # -------------------------------------------------

            st.header(
                "📄 Forensic Report"
            )

            pdf_file = create_pdf_report(
                sender,
                recipient,
                subject,
                date_value,
                len(received_headers),
                all_ips,
                servers,
                spf_result,
                dkim_result,
                dmarc_result,
                indicators
            )

            st.download_button(
                label="⬇️ Download Forensic Report (PDF)",
                data=pdf_file,
                file_name="email_forensic_report.pdf",
                mime="application/pdf"
            )


            st.info(
                "⚠️ These results are forensic indicators only. "
                "They should be correlated with additional evidence "
                "before drawing investigative conclusions."
            )


        except Exception as e:

            st.error(
                f"❌ Error parsing email header: {e}"
            )